In [8]:
import numpy
#先建立一个二维数组(用shape把它重构成二维数组)
l=numpy.linspace(1,121,num=121,dtype="i4")
l.shape=(11,11)



In [19]:
import numpy
arr1=numpy.arange(4).reshape((2,2))
arr2=numpy.array([4,5]).reshape((1,2))
# numpy.concatenate((arr1,arr2),axis=0)
# arr1,arr2
arr1.shape,arr2.shape

((2, 2), (1, 2))

In [3]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
 
print ('沿轴 0 拼接两个数组：')
print (np.concatenate((a,b),0))
print ('\n')
 
print ('沿轴 1 拼接两个数组：')
print (np.concatenate((a,b),1))
print('\n')



第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿轴 0 拼接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 拼接两个数组：
[[1 2 5 6]
 [3 4 7 8]]


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
 
print ('沿轴 0 堆叠两个数组：')
print (np.stack((a,b),0))
print ('\n')
 
print ('沿轴 1 堆叠两个数组：')
print (np.stack((a,b),1))
print('\n')

print('沿轴 2 堆叠两个数组：')
print (np.stack((a,b),2))


第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿轴 0 堆叠两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


沿轴 1 堆叠两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


沿轴 2 堆叠两个数组：
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
